### ISSUE TITLE
您好，我在Ubuntu 20.04.4系统的服务器上下载Sharepoint的链接出现以下提示，请问应该如何解决呢？

### ISSUE THREAD

**Issue by zhaohancheng** [hwfan/DriveDownloader#7]
```
Traceback (most recent call last):
  File "/home/data/t070203/anaconda3/bin/ddl", line 8, in <module>
    sys.exit(simple_cli())
  File "/home/data/t070203/anaconda3/lib/python3.8/site-packages/DriveDownloader/downloader.py", line 126, in simple_cli
    download_single_file(args.url, args.filename, args.thread_number, args.force_back_google)
  File "/home/data/t070203/anaconda3/lib/python3.8/site-packages/DriveDownloader/downloader.py", line 70, in download_single_file
    if len(os.environ["https_proxy"]) > 0:
  File "/home/data/t070203/anaconda3/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'https_proxy'
```
因为学校只对OneDrive免流量，这是把文件从学校提供的OneDrive放到服务器的最后希望了。非常感谢作者的软件！

**Comment by hwfan** [comment]
感谢您使用DriveDownloader！
我们已修复这个问题，请使用`pip install DriveDownloader --force-reinstall --upgrade`升级到最新版。再次感谢您的支持！

**Comment by zhaohancheng** [comment]
更新后可以使用，大大提高了数据上传速度。
再次感谢您的开发和支持！
